package br.com.its.isaude.core.exception.enums;

public enum MessageResponseStatusEnum {

	ERROR_UNEXPECTED, 
	DESCRIPTION_DUPLICATED, 
	CANNOT_BE_LISTED, 
	INSERT_SUCCESS, 
	EDIT_SUCCESS, 
	REMOVE_SUCCESS,
	INSERT_NOT_SUCCESS, 
	EDIT_NOT_SUCCESS, 
	REMOVE_NOT_SUCCESS,
	CNPJ_EXISTS,
	RAZAO_SOCIAL_EXISTS, 
	CNPJ_INVALID	;

}
