package br.com.its.isaude.core.modal.domain;

// Generated 09/12/2013 22:31:28 by Hibernate Tools 4.0.0
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * AgendamentoConsultaMedicaPaciente generated by hbm2java
 */
@Entity
@Table(name = "AGENDAMENTO_CONSULTA_MEDICA_PACIENTE")
public class AgendaConsultMedicalPatient implements java.io.Serializable {

    private Long id;
    private Patiente paciente;
    private MedicalConsultAgenda agendaConsultaMedica;

    public AgendaConsultMedicalPatient() {
    }

    public AgendaConsultMedicalPatient(Patiente paciente, MedicalConsultAgenda agendaConsultaMedica) {
        this.paciente = paciente;
        this.agendaConsultaMedica = agendaConsultaMedica;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "PACIENTE_ID", nullable = false)
    public Patiente getPaciente() {
        return this.paciente;
    }

    public void setPaciente(Patiente paciente) {
        this.paciente = paciente;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "AGENDA_CONSULTA_MEDICA_ID", nullable = false)
    public MedicalConsultAgenda getAgendaConsultaMedica() {
        return this.agendaConsultaMedica;
    }

    public void setAgendaConsultaMedica(MedicalConsultAgenda agendaConsultaMedica) {
        this.agendaConsultaMedica = agendaConsultaMedica;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 29 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 29 * hash + (this.paciente != null ? this.paciente.hashCode() : 0);
        hash = 29 * hash + (this.agendaConsultaMedica != null ? this.agendaConsultaMedica.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AgendaConsultMedicalPatient other = (AgendaConsultMedicalPatient) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}