package br.com.its.isaude.core.modal.domain;

// Generated 09/12/2013 22:31:28 by Hibernate Tools 4.0.0
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AgendaConsultaMedica generated by hbm2java
 */
@Entity
@Table(name = "AGENDA_CONSULTA_MEDICA")
public class MedicalConsultAgenda implements java.io.Serializable {

    private Long id;
    private AgendaDoctor agendaMedico;
    private Date dataConsulta;
    private Date horarioConsulta;
    private String status;
    private Set<AgendaConsultMedicalPatient> agendamentoConsultaMedicaPacientes = new HashSet<AgendaConsultMedicalPatient>();

    public MedicalConsultAgenda() {
    }

    public MedicalConsultAgenda(AgendaDoctor agendaMedico) {
        this.agendaMedico = agendaMedico;
    }

    public MedicalConsultAgenda(AgendaDoctor agendaMedico, Date dataConsulta, Date horarioConsulta, String status, Set<AgendaConsultMedicalPatient> agendamentoConsultaMedicaPacientes) {
        this.agendaMedico = agendaMedico;
        this.dataConsulta = dataConsulta;
        this.horarioConsulta = horarioConsulta;
        this.status = status;
        this.agendamentoConsultaMedicaPacientes = agendamentoConsultaMedicaPacientes;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "ID", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "AGENDA_MEDICO_ID", nullable = false)
    public AgendaDoctor getAgendaMedico() {
        return this.agendaMedico;
    }

    public void setAgendaMedico(AgendaDoctor agendaMedico) {
        this.agendaMedico = agendaMedico;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "DATA_CONSULTA", length = 0)
    public Date getDataConsulta() {
        return this.dataConsulta;
    }

    public void setDataConsulta(Date dataConsulta) {
        this.dataConsulta = dataConsulta;
    }

    @Temporal(TemporalType.TIME)
    @Column(name = "HORARIO_CONSULTA", length = 0)
    public Date getHorarioConsulta() {
        return this.horarioConsulta;
    }

    public void setHorarioConsulta(Date horarioConsulta) {
        this.horarioConsulta = horarioConsulta;
    }

    @Column(name = "STATUS", length = 45)
    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "agendaConsultaMedica")
    public Set<AgendaConsultMedicalPatient> getAgendamentoConsultaMedicaPacientes() {
        return this.agendamentoConsultaMedicaPacientes;
    }

    public void setAgendamentoConsultaMedicaPacientes(Set<AgendaConsultMedicalPatient> agendamentoConsultaMedicaPacientes) {
        this.agendamentoConsultaMedicaPacientes = agendamentoConsultaMedicaPacientes;
    }

    @Override
    public int hashCode() {
        int hash = 7;
        hash = 79 * hash + (this.id != null ? this.id.hashCode() : 0);
        hash = 79 * hash + (this.agendaMedico != null ? this.agendaMedico.hashCode() : 0);
        hash = 79 * hash + (this.dataConsulta != null ? this.dataConsulta.hashCode() : 0);
        hash = 79 * hash + (this.horarioConsulta != null ? this.horarioConsulta.hashCode() : 0);
        hash = 79 * hash + (this.status != null ? this.status.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final MedicalConsultAgenda other = (MedicalConsultAgenda) obj;
        if (this.id != other.id && (this.id == null || !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

}